name: Release

on:
  push:
    branches:
      - master

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  HUSKY: 0  # Bypass husky commit hook for CI

jobs:
  version:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:          
          fetch-depth: 0

      - name: setup caching
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - run: pnpm install

      # - name: create version
      #   uses: changesets/action@master
      #   if: github.ref == 'refs/heads/master'
      #   with:
      #     commit: 'chore(changeset): version update'
      #     title: 'chore(changeset): version update'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create versions PR & prepare publish
        id: changesets
        uses: changesets/action@master
        with:
          version: pnpm ci:version
          commit: 'chore(deploy): Release'
          title: 'chore(deploy): Release'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
